# Generated by Django 4.1.3 on 2022-12-04 17:46

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, verbose_name='Серия')),
                ('number', models.PositiveIntegerField(max_length=8, unique=True, verbose_name='Номер карты')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата выпуска')),
                ('expiry_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Баланс')),
                ('status', models.CharField(choices=[('active', 'Активирована'), ('inactivated', 'Не активирована'), ('overdue', 'Просрочена')], max_length=40, verbose_name='Статус карты')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название покупки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена покупки')),
                ('data_of_purchase', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('bonus_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='cards.bonuscard', verbose_name='Бонусная карта')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
