# Generated by Django 4.1.3 on 2022-12-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер карты'),
        ),
    ]
