# Generated by Django 4.1.3 on 2022-12-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_bonuscard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='number',
            field=models.CharField(max_length=8, unique=True, verbose_name='Номер карты'),
        ),
    ]
