# Generated by Django 4.1.3 on 2022-12-04 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_bonuscard_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bonuscard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='series',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[-A-Z0]+$', 'Неверная серия карты!')], verbose_name='Серия'),
        ),
        migrations.AddConstraint(
            model_name='bonuscard',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='unique_series_number'),
        ),
    ]
